---
# tasks file for nginx
- include_tasks: install-nginx-in-{{ansible_distribution|lower}}.yml
- include_tasks: start-nginx-in-{{ansible_distribution|lower}}.yml
- include_tasks: configure-nginx-in-{{ansible_distribution|lower}}.yml
- include_tasks: common-nginx-tasks.yml
