- name: Configure nginx webserver to use our custom folder while serving web pages in Ubuntu machines
  copy: src=default dest=/etc/nginx/sites-available/default
  notify:
  - Restart nginx web server to apply config changes in Ubuntu machines
